<?php

/**
 * @file
 * Apple News module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function applenews_entity_insert(EntityInterface $entity) {

  try {
    /** @var \Drupal\applenews\ApplenewsManager $manager */
    $manager = \Drupal::service('applenews.manager');
    // On successful post, save response details on entity.
    $manager->postArticle($entity);
  }
  catch (\Exception $e) {
    \Drupal::logger('applenews')->error(t('Error while trying to create an article in Apple News: @error', ['@error' => $e->getMessage()]));
  }
}

/**
 * Implements hook_entity_update().
 */
function applenews_entity_update(EntityInterface $entity) {

  try {
    /** @var \Drupal\applenews\ApplenewsManager $manager */
    $manager = \Drupal::service('applenews.manager');
    // On successful post, save response details on entity.
    $manager->postArticle($entity);
  }
  catch (\Exception $e) {
    \Drupal::logger('applenews')->error(t('Error while trying to update an article in Apple News: @error', ['@err' => $e->getMessage()]));
  }
}

/**
 * Implements hook_entity_delete().
 */
function applenews_entity_delete(EntityInterface $entity) {

  try {
    /** @var \Drupal\applenews\ApplenewsManager $manager */
    $manager = \Drupal::service('applenews.manager');
    // On successful post, save response details on entity.
    $manager->delete($entity);
  }
  catch (\Exception $e) {
    \Drupal::logger('applenews')->error(t('Error while trying to delete an article in Apple News: @error', ['@err' => $e->getMessage()]));
  }
}
